### ISSUE TITLE
Patch for /trunk/psicquic-webservice/src/example/perl/read-all-psicquic.pl

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MICommunity/psicquic#30]
```
I hink it's an error.
```

Original issue reported on code.google.com by `spaqu...@gmail.com` on 3 Jul 2012 at 9:19

Attachments:
* [read-all-psicquic.pl.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-30/comment-0/read-all-psicquic.pl.patch)

**Comment by noedelta** [comment]
This issue was moved to PSICQUIC/psicquic-webservice#4
