### ISSUE TITLE
Patch for /trunk/psicquic-registry/src/example/python/read-registry.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MICommunity/psicquic#34]
```
Adding the codes for Win-Python 3.3
```

Original issue reported on code.google.com by `bioinfor...@gmail.com` on 1 May 2014 at 10:46

Attachments:
* [read-registry.py.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-34/comment-0/read-registry.py.patch)

**Comment by noedelta** [comment]
This issue was moved to PSICQUIC/psicquic-registry#1
