### ISSUE TITLE
Patch for /trunk/psicquic-webservice/src/example/python/read-all-psicquic.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MICommunity/psicquic#35]
```
I update the libraries used, Instead urllib2 I used requests and for XML 
parsing ElementTree
```

Original issue reported on code.google.com by `gunzap...@gmail.com` on 6 May 2014 at 1:09

Attachments:
* [read-all-psicquic.py.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-35/comment-0/read-all-psicquic.py.patch)

**Comment by noedelta** [comment]
This issue was moved to PSICQUIC/psicquic-webservice#1
