### ISSUE TITLE
Problem parsing ... MIF254.xsd, file doesn't exist

### ISSUE THREAD

**Issue by Sinnefa** [MICommunity/psicquic#37]
MIF254.xsd doesn't seem to exist at http://psidev.cvs.sourceforge.net/viewvc/psidev/psi/mi/rel25/src/MIF254.xsd. Is there any fix or workaround available? I suppose the link went down after sourceforge migration, or maybe it's just related to the problems sourceforge is currently having. Anyone can help or explain?

**Comment by noedelta** [comment]
This issue was moved to MICommunity/psidev#607
